"use client";
import {motion,useScroll,useTransform} from "framer-motion";
const projects=[
["01","AGRIHUB","SMART FARMING / IoT / AI","Low-connectivity smart farming with ESP32 sensor intelligence, alerts and farmer-focused decision support.","https://github.com/Tanishak1/AgriHub"],
["02","CAMPUS PLATFORM","COLLEGE / COMMUNITY / WEB","A college-approved digital space connecting students, faculty, projects, research, achievements and collaborative learning.","#"],
["03","THREADBARE ROADS","CIVIC TECH / SIH","Road-condition reporting and infrastructure intelligence designed to turn ground-level problems into actionable information.","https://github.com/Tanishak1/THREADBARE-ROADS"]];
const journey=[["2024","START","Curiosity turned into code."],["2025","BUILD","Java + full-stack projects and real-world learning."],["2026","LEAD","President, Codezy Coding Society."],["NOW","SHIP","AgriHub, campus tech and practical AI products."]];
export default function Home(){const {scrollYProgress}=useScroll();const y=useTransform(scrollYProgress,[0,1],[0,-180]);return <main>
<motion.div className="progress" style={{scaleX:scrollYProgress}}/>
<nav><a className="logo" href="#">T/T</a><div><a href="#about">ABOUT</a><a href="#work">WORK</a><a href="#contact">CONTACT</a></div></nav>
<section className="hero"><motion.div className="scribble" animate={{rotate:[-8,8,-8]}} transition={{duration:5,repeat:Infinity}}>BUILD<br/>WHAT<br/>MATTERS ↗</motion.div><div className="heroMeta">PORTFOLIO — 2026 <b>INDIA / AVAILABLE</b></div><motion.h1 initial={{y:140}} animate={{y:0}} transition={{duration:1,ease:[.2,.8,.2,1]}}>TANISHAK<br/><i>TYAGI</i></motion.h1><div className="heroFoot"><p>FULL STACK DEVELOPER<br/>JAVA DEVELOPER<br/>AI ENTHUSIAST</p><p>SCROLL TO EXPLORE ↓</p></div></section>
<div className="tape"><div>DESIGN ✦ CODE ✦ CREATE ✦ LEAD ✦ EXPERIMENT ✦ SHIP ✦ DESIGN ✦ CODE ✦ CREATE ✦ LEAD ✦</div></div>
<section id="about" className="paper"><motion.div className="note" style={{y}}><span>HELLO!</span><br/>I TURN IDEAS<br/>INTO PRODUCTS.</motion.div><p className="kicker">[ WHO AM I? ]</p><h2>A STUDENT.<br/>A BUILDER.<br/><em>A LEADER.</em></h2><p className="copy">I'm Tanishak Tyagi, a Computer Science student at RKGITM. I build full-stack products, experiment with AI and IoT, and lead developer communities. I care about work that solves a real problem—not just another demo.</p></section>
<section id="work" className="work"><header><span>[ SELECTED WORK ]</span><span>DRAG YOUR EYES ↓</span></header><h2>THINGS I'VE<br/><i>BUILT.</i></h2>{projects.map((p,i)=><motion.a className={"card c"+i} href={p[4]} target={p[4]==="#"?undefined:"_blank"} key={p[1]} initial={{rotate:i%2?3:-3,y:90,opacity:0}} whileInView={{rotate:i%2?1:-1,y:0,opacity:1}} whileHover={{rotate:0,scale:1.015}} viewport={{once:true,amount:.2}}><span className="num">{p[0]}</span><small>{p[2]}</small><h3>{p[1]}</h3><p>{p[3]}</p><b>OPEN ↗</b></motion.a>)}</section>
<section className="journey"><div className="stamp">UNFILTERED<br/>JOURNEY</div><p>[ TIMELINE ]</p><h2>NOT A STRAIGHT<br/>LINE. <i>A REAL ONE.</i></h2><div className="rail">{journey.map((j,i)=><motion.div className="stop" key={j[0]} initial={{opacity:.2}} whileInView={{opacity:1}}><b>{j[0]}</b><span>{j[1]}</span><p>{j[2]}</p><i>{i+1}</i></motion.div>)}</div></section>
<section className="skills"><p>[ TOOLBOX / PLAYGROUND ]</p><div>JAVA ✦ JAVASCRIPT ✦ NEXT.JS ✦ REACT ✦ NODE.JS ✦ SQL ✦ ESP32 ✦ AI ✦</div></section>
<footer id="contact"><span>ONE LAST THING...</span><h2>LET'S MAKE<br/><i>SOMETHING</i><br/>REAL.</h2><div><a href="https://github.com/Tanishak1" target="_blank">GITHUB ↗</a><b>TANISHAK TYAGI © 2026</b><a href="mailto:">EMAIL ↗</a></div></footer>
<div className="dock"><a href="#">HOME</a><a href="#work">WORK</a><a href="#about">ABOUT</a><a href="#contact">CONTACT</a></div>
</main>}